name: Feature request
description: Propose a new feature or improvement
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem to solve
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
    validations:
      required: true
